const state={jobs:[],filtered:[]};
const $=id=>document.getElementById(id);
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const unique=(key)=>[...new Set(state.jobs.map(j=>j[key]).filter(Boolean))].sort();
function fill(id,key){unique(key).forEach(v=>$(id).insertAdjacentHTML('beforeend',`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`))}
function ageLabel(date){const days=Math.max(0,Math.floor((Date.now()-new Date(date+'T00:00:00Z'))/86400000));return days===0?'Today':days===1?'1 day ago':`${days} days ago`}
function render(){const q=$('search').value.trim().toLowerCase(),domain=$('domain').value,level=$('level').value,workplace=$('workplace').value,min=+$('score').value;state.filtered=state.jobs.filter(j=>!q||[j.title,j.company,j.location,j.domain,j.level,j.skills].join(' ').toLowerCase().includes(q)).filter(j=>!domain||j.domain===domain).filter(j=>!level||j.level===level).filter(j=>!workplace||j.workplace===workplace).filter(j=>j.score>=min).sort((a,b)=>b.score-a.score||new Date(b.posted)-new Date(a.posted));$('resultCount').textContent=`${state.filtered.length} ${state.filtered.length===1?'job':'jobs'}`;$('empty').hidden=state.filtered.length>0;$('jobs').innerHTML=state.filtered.map(j=>`<article class="job-row"><div class="score ${j.score<50?'low':j.score<70?'medium':''}" title="Worth applying score">${j.score}</div><div class="role"><h2 title="${escapeHtml(j.title)}">${escapeHtml(j.title)}</h2><p>${escapeHtml(j.company)} · ${escapeHtml(j.level||'Level not specified')}</p></div><div class="cell"><span class="tag">${escapeHtml(j.domain)}</span></div><div class="cell"><strong>${escapeHtml(j.location)}</strong><small>${escapeHtml(j.workplace||'Not specified')}</small></div><div class="fresh">${ageLabel(j.posted)}<small>${escapeHtml(j.status)}</small></div><a class="apply" href="${escapeHtml(j.applyUrl)}" target="_blank" rel="noopener noreferrer">Apply ↗</a></article>`).join('')}
async function init(){try{const res=await fetch(`jobs.json?v=${Date.now()}`);const data=await res.json();state.jobs=data.jobs;$('totalJobs').textContent=state.jobs.length;$('highScore').textContent=state.jobs.filter(j=>j.score>=85).length;$('newJobs').textContent=state.jobs.filter(j=>(Date.now()-new Date(j.posted+'T00:00:00Z'))/86400000<=7).length;$('updated').textContent=`Last verified ${new Date(data.lastUpdated).toLocaleString()}`;fill('domain','domain');fill('level','level');fill('workplace','workplace');render()}catch(e){$('updated').textContent='Job feed unavailable';$('empty').hidden=false;$('empty').textContent='The job feed could not be loaded. Please try again shortly.'}}
['search','domain','level','workplace','score'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('clear').addEventListener('click',()=>{['search','domain','level','workplace'].forEach(id=>$(id).value='');$('score').value='0';render()});init();
